import Head from "next/head";
import Image from "next/image";

export default function Home({ fruits }) {
  console.log(fruits);
  return (
    <div className="h-screen w-full font-fira">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-green-700">Hello</h1>
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  const endpoint = `https://thawing-fortress-03877.herokuapp.com/api/fruits/all`;
  const res = await fetch(endpoint);
  const fruits = await res.json();

  return {
    props: {
      fruits,
    }, // will be passed to the page component as props
  };
}
