import Head from "next/head";
import Image from "next/image";

import { FruitCard } from "../components/FruitCard";

export default function Home({ fruits }) {
  console.log(fruits);
  return (
    <div className="relative h-screen w-full font-poppins">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <img
        className="absolute top-10 left-10 w-12 h-12"
        src="/images/blueberry.svg"
        alt="blueberry"
      />

      <img
        className="absolute top-16 right-20 w-12 h-12"
        src="/images/strawberry.svg"
        alt="blueberry"
      />

      <img
        className="absolute top-56 left-28 w-12 h-12"
        src="/images/apple.svg"
        alt="blueberry"
      />

      <main className="w-full h-full mx-auto text-center py-10">
        <h1 className="text-brand-black font-semibold uppercase text-[45px] max-w-[40rem] mx-auto">
          Fruit Nutrition facts and Health benefits
        </h1>

        <div class="max-w-4xl mx-auto mt-4 py-10 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-5">
          {fruits.map((fruit) => (
            <FruitCard {...fruit} />
          ))}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  const endpoint = `https://thawing-fortress-03877.herokuapp.com/api/fruits/all`;
  const res = await fetch(endpoint);
  const fruits = await res.json();

  return {
    props: {
      fruits,
    }, // will be passed to the page component as props
  };
}
